#!/bin/bash

# Script must be run as root
if [ $(id -u) -ne 0 ]; then
    echo "Error: This program can only be used by the root user";
    exit 1;
fi

function usage {
    local script_name="$(basename "$0")";
    echo "Usage: /etc/init.d/${script_name} {start|stop|status|restart}";
}

case "$1" in
    status)
        for status_command in \
            "service flower status" \
            "service celerybeat status" \
            "service uwsgi status atmosphere" \
            "service uwsgi status troposphere" \
            "service nginx status" \
            "service celeryd status"; do

            # Echo command being run
            echo $status_command;

            # Perform command (and indent the output)
            $status_command 2>&1 | awk '{ print "    " $0 }'
        done
        ;;
    start | stop | restart)
        for name in flower celerybeat uwsgi nginx celeryd; do
            # Echo command being run
            echo service "$name" "$1";

            # Perform action
            service "$name" "$1"

            # Fail/exit if action fails
            if [ $? -ne 0 ]; then
                echo "Warning: service $name $1 failed" 2>&1;
                echo "rerun that command, to see specific errors" 2>&1;
            fi
        done
        ;;
    *) usage;
        ;;
esac
