- name: create directory
  file: path={{ VIRTUAL_ENV_BASE_DIR }} state=directory

- name: Remove virtualenv
  file:
    path: "{{ VIRTUAL_ENV_FULL_PATH }}"
    state: absent
  when: REINSTALL | default(False)

- name: Create pyenv virtualenv {{ VIRTUAL_ENV_FULL_PATH }}
  shell: |
    export PYENV_ROOT={{ PYENV_ROOT }} \
           PATH="{{ PYENV_ROOT }}/bin:$PATH"
    eval "$(pyenv init -)"
    virtualenv -p $({{ PYENV_ROOT }}/bin/pyenv which python) {{ VIRTUAL_ENV_FULL_PATH }}
  args:
    creates: "{{ VIRTUAL_ENV_FULL_PATH }}"
