- name: create directory
  file: path={{ VIRTUAL_ENV_BASE_DIR }} state=directory

- name: Remove virtualenv
  file:
    path: "{{ VIRTUAL_ENV_FULL_PATH }}"
    state: absent
  when: REINSTALL | default(False)

- name: Create virtualenv
  command: virtualenv {{ VIRTUAL_ENV_FULL_PATH }} creates="{{ VIRTUAL_ENV_FULL_PATH }}"
  register: output

- debug: var=output.stdout_lines
  when: CLANK_VERBOSE | default(False)
