---
- name: Create a directory to store temporary files
  file:
    path: "{{ role_path }}/build"
    state: directory

- template:
    src: "{{ role_path }}/templates/openssl-server.cnf.j2"
    dest: "{{ role_path }}/build/openssl-server.cnf"

- name: Make a certificate signing request
  command: >
    openssl req
      -config "{{ role_path }}/build/openssl-server.cnf"
      -newkey rsa:4096
      -sha256
      -nodes
      -out "{{ TLS_CERT_REQUEST_DEST }}"
      -keyout "{{ TLS_CERT_PRIVATE_KEY_DEST }}"
      -outform PEM
