---
# tasks file for setup-webserver-user-group

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "defaults.yml"
  tags: vars

- name: add webserver-user for user and group permissions
  file: path={{ APP_BASE_DIR }} owner={{ WEBSERVER_USER }} group={{ WEBSERVER_USER }} mode="g+rw" recurse=yes

- name: add vagrant user to webserver_user when value present
  user: name=vagrant group={{ WEBSERVER_USER }}
  when: VAGRANT

- name: turn off apache
  service: name={{ APACHE }} state=stopped enabled=no
  failed_when: False
