# We must remove the line that we want to insert, otherwise ansible will not
# respect "insertbefore". It's only respected when inserting lines that don't
# already exist, so if you want to insert a line, you must remove it first.
#
# https://github.com/ansible/ansible/issues/21176#issuecomment-278557219
#
- block:
    - name: "Explicitly remove database user, to ensure inserting in the right location"
      lineinfile:
          dest: "/etc/postgresql/{{ DB_VERSION }}/main/pg_hba.conf"
          regexp: "^local +all +{{ DBUSER }} +md5"
          state: absent

    - name: "Give database user ({{ DBUSER }}) password authentication on domain sockets"
      lineinfile:
        dest: "/etc/postgresql/{{ DB_VERSION }}/main/pg_hba.conf"

        # Note: We must insert 'line' before this more restrictive line, if it exists.
        insertbefore: "^local +all +all +peer"

        line: "local   all              {{ DBUSER }}                  md5"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - postgres

- block:
    - name: Check if it needs initialization
      shell: test -f {{ postgresql_data_directory }}/PG_VERSION
      register: postgresql_needs_init
      changed_when: false
      failed_when: false
      tags:
        - postgresql_config

    - name: Initialize the DB with init.d
      shell: /usr/pgsql-9.6/bin/postgresql-{{ DB_VERSION }}-setup initdb
      environment:
        PGDATA: "{{ postgresql_data_directory }}"
      when: >
        postgresql_needs_init.rc > 0
      tags:
        - postgresql_config

    - name: "Explicitly remove database user, to ensure inserting in the right location"
      lineinfile:
          dest: "{{ postgresql_hba_config_file }}"
          regexp: "^local +all +{{ DBUSER }} +md5"
          state: absent

    - name: "Give database user ({{ DBUSER }}) password authentication on domain sockets"
      lineinfile:
        dest: "{{ postgresql_hba_config_file }}"
        # Note: We must insert 'line' before this more restrictive line, if it exists.
        insertbefore: "^local +all +all +peer"

        line: "local   all              {{ DBUSER }}                  md5"
      notify:
        - Restart PostgreSQL server
  when: ansible_distribution == 'CentOS'
  tags:
    - postgres