---
# tasks file for noc-enable-new-relic
- block:

  - name: Fail if TARGET_HOME is not set
    fail: msg="Wait! Variable TARGET_HOME must be set."
    when: TARGET_HOME == ""

  - name: Fail if MODULE_NAME is not set
    fail: msg="Wait! Variable MODULE_NAME must be set."
    when: MODULE_NAME == ""

  - name: Stat the settings path
    stat: path="{{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ LOCAL_SETTINGS }}"
    register: settings_path

  - name: Fail if settings does not exist
    fail: msg="Wait! {{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ LOCAL_SETTINGS }} should exist"
    when: settings_path.stat.exists == False

  - name: ensure role has local files directory
    local_action: >
        file path={{ role_path }}/files state=directory mode=0755

  - name: ensure new_relic settings file exists
    file:
      path: "{{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }}"
      state: touch
      mode: 0644

  - name: ensure new_relic extras directory exists
    file:
      path: "{{ TARGET_HOME }}/{{ NEW_RELIC_EXTRAS }}"
      state: directory
      mode: 0755

  - name: Templated New Relic settings to '{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }}'
    template:
      src: "{{ role_path }}/templates/new_relic.py.j2"
      dest: "{{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }}"

  - name: Templated app_newrelic.ini to newrelic.ini
    template:
      src: "{{ role_path }}/templates/app_newrelic.ini.j2"
      dest: "{{ TARGET_HOME }}/{{ NEW_RELIC_EXTRAS }}/{{MODULE_NAME}}_newrelic.ini"

  when: NEW_RELIC is defined
