---
# defaults file for app-install-instance-deploy-automation

APP_BASE_DIR:

SSH_PRIV_KEY:
SSH_PUB_KEY:

INSTANCE_DEPLOY_AUTOMATION_DIR:
INSTANCE_DEPLOY_AUTOMATION_HOSTS_FILE:
INSTANCE_DEPLOY_AUTOMATION_GROUP_VARS_FOLDER:
