YUM_PACKAGES:
  packages:
    - https://rpm.nodesource.com/pub_4.x/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm
    - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm

INITIAL_PACKAGES:
  packages:
    - "@Development tools" #gcc, make

DEV_PACKAGES:
  packages:
    - libffi-devel #yum
    - python #yum
    - openssl #yum
    - postgresql96-server #yum
    - postgresql96-contrib #yum
    - python-psycopg2 #yum
    - postgresql96-devel #yum
    - postgresql96-libs #yum
    - python-devel #yum
    - openldap-devel #yum
    - m2crypto #yum
    - swig #yum
    - redis #epel
    - git #yum
    - nodejs #yum
    - python-setuptools #yum
    - ufw #yum

LIB_PACKAGES:
  packages:
    - libxml2-devel #yum
    - libxslt-devel #yum
    - tkinter #yum
    - tk-devel #yum
    - zlib-devel #yum

NGINX_PACKAGES:
  packages:
    - uwsgi #yum
    - uwsgi-plugin-python #yum
    - nginx #yum

APACHE: httpd