---
- name: Post deployment of atmosphere/troposphere
  hosts: all
  roles:
    - { role: atmosphere-include-startup,
        tags: ['atmosphere'] }
    - { role: sanitary-sql-access,
        when: SETUP_SANITARY_SQL_ACCESS is defined and SETUP_SANITARY_SQL_ACCESS == true }
  tags:
    - post-install
