---

- name: APT update cache as separate step
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
  failed_when: false

- name: APT upgrade packages
  apt:
    upgrade: dist
  when: ansible_pkg_mgr == "apt"

- name: Yum
  yum:
    update_cache: yes
    name: "*"
    state: latest
  when: ansible_pkg_mgr == "yum"
